server:
  port: 8899

spring:
  application:
    name: notificator
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  sqs:
    request-video-notificator-queue: sqs-request-video-notificator